hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('hotelmanagement.urls', namespace='abc')),
    path('admin/', admin.site.urls),
    path('api/', include('hotelmanagement.api.urls', namespace='hapi')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/hotelmanagement/urls.py
from django.urls import path
from . import views

app_name = 'hotelmanagement_namspace'

urlpatterns = [
    path('producttypes', views.producttype_list, name='producttypes'),
    path('producttypes/create', views.producttype_create, name='producttypes_create'),
    path('producttypes/edit/<int:id>', views.producttype_edit, name='producttypes_edit'),
    path('producttypes/delete/<int:id>', views.producttype_delete, name='producttypes_delete'),

    path('roomtypes', views.roomtype_list, name='roomtypes'),
    path('roomtypes/create', views.roomtype_create, name='roomtypes_create'),
    path('roomtypes/edit/<int:id>', views.roomtype_edit, name='roomtypes_edit'),
    path('roomtypes/delete/<int:id>', views.roomtype_delete, name='roomtypes_delete'),

    path('clients', views.cient_list, name='clients'),
    path('clients/create', views.client_create, name='client_create'),
    path('clients/edit/<int:id>', views.client_edit, name='client_edit'),
    path('clients/delete/<int:id>', views.client_delete, name='client_delete'),

    path('configs', views.config_list, name='configs'),
    path('configs/create', views.config_create, name='config_create'),
    path('configs/edit/<int:id>', views.config_edit, name='config_edit'),
    path('configs/delete/<int:id>', views.config_delete, name='config_delete'),

    path('paymenttypes', views.paymenttype_list, name='paymenttypes'),
    path('paymenttypes/create', views.paymenttype_create, name='paymenttype_create'),
    path('paymenttypes/edit/<int:id>', views.paymenttype_edit, name='paymenttype_edit'),
    path('paymenttypes/delete/<int:id>', views.paymenttype_delete, name='paymenttype_delete'),

    path('products', views.product_list, name='products'),
    path('products/create', views.product_create, name='product_create'),
    path('products/edit/<int:id>', views.product_edit, name='product_edit'),
    path('products/delete/<int:id>', views.product_delete, name='product_delete'),

    path('rooms', views.room_list, name='rooms'),
    path('rooms/create', views.room_create, name='room_create'),
    path('rooms/edit/<int:id>', views.room_edit, name='room_edit'),
    path('rooms/delete/<int:id>', views.room_delete, name='room_delete'),

    path('persons', views.person_list, name='persons'),
    path('persons/create', views.person_create, name='person_create'),
    path('persons/edit/<int:id>', views.person_edit, name='person_edit'),
    path('persons/delete/<int:id>', views.person_delete, name='person_delete'),
    path('persons/change_password/<int:id>', views.person_changepassword, name='change_password'),

    path('report/houseskeeping', views.report_houseskeeping, name='report_houseskeeping'),
    path('report/cancel', views.report_cancel, name='report_cancel'),
    path('report/noshow', views.report_noshow, name='report_noshow'),
    path('report/breakfast', views.report_breakfast, name='report_breakfast'),
    path('report/pending_checkin', views.report_checkin, name='report_pending_checkin'),
    path('report/pending_checkout', views.report_checkout, name='report_pending_checkout'),
    path('report/pending_inhouse', views.report_inhouse, name='report_inhouse'),
    path('report/pamentbymonth', views.report_paymentbymoth, name='report_pamentbymonth'),
    path('report/paymentbydate', views.report_paymentbydate, name='report_paymentbydate'),
    path('report/roompayment', views.report_roompayment, name='report_roompayment'),
    path('report/extrapayment', views.report_extrapayment, name='report_extrapayment'),

    path('login', views.login_auth, name='login'),
    path('logout', views.logout_auth, name='logout'),
    path('notify_nummer', views.notify_nummer, name='notify_nummer'),
    path('quick_search', views.quick_search, name='quick_search'),
    path('', views.index, name='index'),

]

hotel/templates/dashboard/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{{ title }}{% endblock %}
{% block container %}
    {% load humanize %}
    <div class="row">
        <div class="col-xl-4 col-sm-6 mb-4">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-comments"></i>
                    </div>
                    <div class="mr-5">{{ pennding_checkin }} Pending Check-in!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{% url 'hotelmanagement_namspace:report_pending_checkin' %}">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-4 col-sm-6 mb-4">
            <div class="card text-white bg-warning o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-list"></i>
                    </div>
                    <div class="mr-5">{{ in_house }} In-house!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{% url 'hotelmanagement_namspace:report_inhouse' %}">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-4 col-sm-6 mb-4">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-shopping-cart"></i>
                    </div>
                    <div class="mr-5">{{ pennding_checkout }} Pending Check-out!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{% url 'hotelmanagement_namspace:report_pending_checkout' %}">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
                </a>
            </div>
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Data Table Room Status
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Capacity</th>
                        <th>Room Status</th>
                        <th>Room Type</th>
                        <th>Option</th>
                    </tr>
                    {% for item in rooms %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                <a href="{% url 'hotelmanagement_namspace:room_edit' id=item.id %}">{{ item.name }}</a>
                            </td>
                            <td>
                                {{ item.price | intcomma }} VND
                            </td>
                            <td>
                                {{ item.capacity }}
                            </td>
                            <td>
                                {{ item.room_status }}
                            </td>
                            <td>
                                {{ item.room_type }}
                            </td>
                            <td>
                                <a href="{% url 'hotelmanagement_namspace:room_delete' id=item.id %}"
                                   onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}


                </table>
            </div>
        </div>
        <div class="card-footer small text-muted">
            <div class="pagination">
    <span class="step-links">
        {% if rooms.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ rooms.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ rooms.number }} of {{ rooms.paginator.num_pages }}.
        </span>

        {% if rooms.has_next %}
            <a href="?page={{ rooms.next_page_number }}">next</a>
            <a href="?page={{ rooms.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
            </div>
        </div>
    </div>
{% endblock %}