hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('hotelmanagement.urls', namespace='abc')),
    path('admin/', admin.site.urls),
    path('api/', include('hotelmanagement.api.urls', namespace='hapi')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/hotelmanagement/urls.py
from django.urls import path
from . import views

app_name = 'hotelmanagement_namspace'

urlpatterns = [
    path('producttypes', views.producttype_list, name='producttypes'),
    path('producttypes/create', views.producttype_create, name='producttypes_create'),
    path('producttypes/edit/<int:id>', views.producttype_edit, name='producttypes_edit'),
    path('producttypes/delete/<int:id>', views.producttype_delete, name='producttypes_delete'),

    path('roomtypes', views.roomtype_list, name='roomtypes'),
    path('roomtypes/create', views.roomtype_create, name='roomtypes_create'),
    path('roomtypes/edit/<int:id>', views.roomtype_edit, name='roomtypes_edit'),
    path('roomtypes/delete/<int:id>', views.roomtype_delete, name='roomtypes_delete'),

    path('clients', views.cient_list, name='clients'),
    path('clients/create', views.client_create, name='client_create'),
    path('clients/edit/<int:id>', views.client_edit, name='client_edit'),
    path('clients/delete/<int:id>', views.client_delete, name='client_delete'),

    path('configs', views.config_list, name='configs'),
    path('configs/create', views.config_create, name='config_create'),
    path('configs/edit/<int:id>', views.config_edit, name='config_edit'),
    path('configs/delete/<int:id>', views.config_delete, name='config_delete'),

    path('paymenttypes', views.paymenttype_list, name='paymenttypes'),
    path('paymenttypes/create', views.paymenttype_create, name='paymenttype_create'),
    path('paymenttypes/edit/<int:id>', views.paymenttype_edit, name='paymenttype_edit'),
    path('paymenttypes/delete/<int:id>', views.paymenttype_delete, name='paymenttype_delete'),

    path('products', views.product_list, name='products'),
    path('products/create', views.product_create, name='product_create'),
    path('products/edit/<int:id>', views.product_edit, name='product_edit'),
    path('products/delete/<int:id>', views.product_delete, name='product_delete'),

    path('rooms', views.room_list, name='rooms'),
    path('rooms/create', views.room_create, name='room_create'),
    path('rooms/edit/<int:id>', views.room_edit, name='room_edit'),
    path('rooms/delete/<int:id>', views.room_delete, name='room_delete'),

    path('persons', views.person_list, name='persons'),
    path('persons/create', views.person_create, name='person_create'),
    path('persons/edit/<int:id>', views.person_edit, name='person_edit'),
    path('persons/delete/<int:id>', views.person_delete, name='person_delete'),
    path('persons/change_password/<int:id>', views.person_changepassword, name='change_password'),

    path('report/houseskeeping', views.report_houseskeeping, name='report_houseskeeping'),
    path('report/cancel', views.report_cancel, name='report_cancel'),
    path('report/noshow', views.report_noshow, name='report_noshow'),
    path('report/breakfast', views.report_breakfast, name='report_breakfast'),
    path('report/pending_checkin', views.report_checkin, name='report_pending_checkin'),
    path('report/pending_checkout', views.report_checkout, name='report_pending_checkout'),
    path('report/pending_inhouse', views.report_inhouse, name='report_inhouse'),
    path('report/pamentbymonth', views.report_paymentbymoth, name='report_pamentbymonth'),
    path('report/paymentbydate', views.report_paymentbydate, name='report_paymentbydate'),
    path('report/roompayment', views.report_roompayment, name='report_roompayment'),
    path('report/extrapayment', views.report_extrapayment, name='report_extrapayment'),

    path('login', views.login_auth, name='login'),
    path('logout', views.logout_auth, name='logout'),
    path('notify_nummer', views.notify_nummer, name='notify_nummer'),
    path('quick_search', views.quick_search, name='quick_search'),
    path('', views.index, name='index'),

]

hotel/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Hi{% endblock %} | HOANG LOC hotel</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

</head>

<body id="page-top" onclick="remove_quick_search()">
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="{% url 'hotelmanagement_namspace:index' %}">HOANG LOC hotel</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle">
        <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" method="get" action="/persons">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search Username, Email, Name..." aria-label="Search"
                   aria-describedby="basic-addon2" name="q" id="txtQuickSearch">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
            <div id="quick-serch-bar" class="quick-search-bar"></div>
        </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
        <div id="noti-nummer" style="display: inherit;"></div>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                {% if user.users.avatar %}
                    <img src="{{ user.users.avatar.url }}" alt="{{ user.first_name }}"
                         style="width: 20px; border-radius: 10px;">
                {% else %}
                    <img src="{% static "images/no-avatar.png" %}" alt="{{ user.first_name }}"
                         style="width: 20px; border-radius: 10px;">
                {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:person_edit' id=user.id %}">Profile</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:change_password' id=user.id %}">Change
                    Password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:logout' %}">Logout</a>
            </div>
        </li>
    </ul>

</nav>

<div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Report</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <h6 class="dropdown-header">Payment:</h6>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_paymentbydate' %}">Daily
                    Payment</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_pamentbymonth' %}">Monthly
                    Payment</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_extrapayment' %}">Extra
                    Payment</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_roompayment' %}">Room
                    Payment</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">HouseShkeeping:</h6>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_houseskeeping' %}">Report</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">Reservation:</h6>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_cancel' %}">Cancelation</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_noshow' %}">No-show</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_breakfast' %}">Breakfast List</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">Front Desk:</h6>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_pending_checkin' %}">Pending
                    Check-in</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_pending_checkout' %}">Pending
                    Check-out</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:report_inhouse' %}">Guest In-House
                    Detail</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Client</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:clients' %}">List</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:client_create' %}">Create</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Payment Type</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:paymenttypes' %}">List</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:paymenttype_create' %}">Create</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Room</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:roomtypes' %}">Categories</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:roomtypes_create' %}">New Category</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:room_create' %}">Create Room</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:rooms' %}">Rooms</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Service</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:producttypes' %}">Categories</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:producttypes_create' %}">New
                    Category</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:product_create' %}">Create Service</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:products' %}">Services</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>User</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:persons' %}">List</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:person_create' %}">Create</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Config</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:configs' %}">List</a>
                <a class="dropdown-item" href="{% url 'hotelmanagement_namspace:config_create' %}">Create</a>
            </div>
        </li>
    </ul>

    <div id="content-wrapper">

        <div class="container-fluid">

            <!-- Breadcrumbs-->
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">{{ title }}</li>
            </ol>

            <!-- Page Content -->
            <div class="card mb-3">
                {% block container %}
                    <div class="card-header">
                        <i class="fas fa-table"></i>
                        Data Table Example
                    </div>
                    <div class="card-body">

                    </div>
                    <div class="card-footer small text-muted"></div>
                {% endblock %}

            </div>

        </div>
        <!-- /.container-fluid -->

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>HOANG LOC hotel © 2019</span>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
<div style="display: none" id="loading-quick-search-bar">
    <div style="width: 100%; text-align: center;">
        <img style="width: 60px;" src="{% static "images/loading.gif" %}" alt="Loading...">
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin.min.js' %}"></script>
{% if user.is_authenticated %}
    <script>
        $('#quick-serch-bar').hide();
        $.ajax({
            url: "/notify_nummer", success: function (result) {
                $('#noti-nummer').html(result)
            }
        });
        $('#txtQuickSearch').keyup((key) => {
            $('#quick-serch-bar').show();
            $('#quick-serch-bar').html($('#loading-quick-search-bar').html());
            q = $('#txtQuickSearch').val();
            if (q.length > 0) {
                $.ajax({
                    url: "/quick_search?q=" + $('#txtQuickSearch').val(), success: function (result) {
                        $('#quick-serch-bar').html(result)
                    }
                });
            } else {
                $('#quick-serch-bar').hide();
            }
        });
        function remove_quick_search(){
            $('#quick-serch-bar').hide();
        }
    </script>
{% endif %}


</body>

</html>